language: java
jdk:
- openjdk8
env:
  global:
  - secure: MMMlczZR0puB32OhxZ20TOWRVicVWAqe2bzNAkreT1xa200g04d+wRfNJgWJLuL4hT7e6TDlOrbWbJPwEa5fheSytqnKrdJyDsxgSzGUtEErn/GPDQDh0hZEQO8UZHiHnXIA0QFgDoMnvkGTm/L72MsXvF8cut18ElyHHiBNe8a8d6QwlD4OBdomF5F7/Fyq2NO5Dfbr/ySkC8IL/GF2f5JHEnXajUTFYMQShfWXGNaVdNBvrpgq3+7J/oHo8O1Hfq5Aw3nHtNackVHrFbWd6p4kYX3KliXZCHIo9VOFJaN/bZq5FXUp3mqa23r1zQdTygthRuDd/+UQSQJ3iE93oqeig2ebVHF3MZHclN6hXvsJpBB0W4L2vrhfXQ3zByMjn3oRUIPyiuMXcBXP00z5gbrSnJZBl4WA6jPG0o7toISvzAXTGcr9vrVS/hN9+c62CoulBEz7gGdnWYnPq6Ff2JwFr5eBrZkUDprPuWwcoL0DGKqHnq7IqNe1356wOsO1PfqeZAH6yOxwE4MzeaSNYnjw9UupZIJFpcXHBepG8YehAy8wFLG+292pqWdAvrdb/PxOO+355kGfyGIHEsmI1gjWeNcuM6tO2VcTecSKhHhJfJqtMAusjQ9nLhg/tr9mR9uAudqRt2LQ8qFm7jFXTpF/AbtcfXuLV85yjEvmDMA=
  - secure: ABoKZIvZi3jltDypafDSGdzkb86UxFB0MowB6kQq0/pZ4IcKpO5WZrcRJRUFX36GTs/9iZi7TC9m+J2E9OiVxgFYzH4Xfaiohpoiy2RXGeuOrflWqMA0UKisnPwbftm0372KcyisyU6An2tdi59G0OavAoK4pglYE79baP1K6ScTPbFUe4nfc4SQUoGB4hHM/+ZyfidUKhLbCiBmdS6kZzoumYIZYIBn4u+1aaij1kJNjjR++aeAzO4D6aV8Vh0zF9A0Y/ji5wPBLHkzEqPl5PGRbl9hhZk5en1qQ2l64NWWIkknplCgY7SYOKrH5dx2e1r4LOeNDIuOo4aH0jy1IYUuHiZ7Sn++TOYMwNVRxdtiq7umYUtzuk6J4emKxcNHeWa58TdxywSSCGuIl8bj5MQ6DxR7U5UbqlAgFIWtdEo4emls263Kmd2qfkDVFSlQ3maWqp72vXfdBT3yphh7TGWhhALek6dhGtlleDuPvIRWxU/iEw+IaywAW+dJmKFvbzzfMSHy4f+JfB4oBVlrWY5fw8XIi4RqVbN1gKnx94VacIer9Xk6gJps0lfLkfEk2WEsRVs/cFSgB0yPsQzYqXfXbkrSxeOxpGMoc9/7JsIVvttZOmF6czD6x1fyCMwfHOIPPsJJZwtoAw8u7Mt36U/RM3/Q+crq0LeJFMZnEcI=
  - secure: HbifZvjsOqsIDlznucw0vX8rZdhuPcWA0A5lGw/km0MERZFDWG69tqeUyEEBZdMg9QYBVqsQ2CX+BIPvdPFYWDFiYLkrbD7q/E6t79wRh2dQdZ0guT5UQbwtwpapPeHkRfRHIHO+yKn5Lhf0DfERe0m/pv0sz24zTPvkidDzLRr8I8ig76WILANUhENjAVYVYe2rL5Qkj5iSV8PboGmURgF06eBvuJkNkRX2AQRHNIkJ1Cknes8F1wiYK5JW17ctSg1Hz875NN3I+G4vNZVz1UN9RC/24toG7lEgOOUcCo9+zFhLZaNP7JhDd6zdd3Ld7vR6Kg8vh8wJGZgRDaG3uLbqkpUt0ByDb6919caYoz1dShfw+tBmZEnvSWIBKs8w9yhDJdTMWncIeTqSbO0SjfT41TLoJuV2V0DAmcMgVIj6xjsviGSMIMDYLf6zh8K6FZ1OfzgBRpfaKBWtkxYM13qwFehEvRAMZM7aj02o53vcSeoySP58qqNDBD3YXnrpFXHDKw6l8SvPEc68g1YSy6SjJ32kVUMe8Pq1T0actoW85H/75fnOOniQ0Z/UhF6k8m9vBEjHKi9Kugg0RlKKUietR7UiwXEvubgI6EYckSz0T5ZAzLkaA6QtnzqRCMdynZCBFPhrTOTi0yAbMLZbBn0a3PYucVPxoL9JV30kUio=
  - secure: L6Qg085dYrf5y6Vi3UkXHjy/k4g8cq4bwpbNjH9LtXJeS4tqxEChJ834LjtChBnDxAmdmJQGpkuNjcyaAvTgu1vqo4FBlvDZUghH2Ggom4yYVASBXNI0vCvW52P260YaBsHPy1/kXDcXplAb9IfqGraoAwMDz486yPulZEcmbq8jkxqzHqtIjvQUZYaHQIexQoah44IeqecyH9ahv0UpvBVsbCT3qOagiqIo6F7SPJw//ekZcv0X+5Vz+JFp+pphX5Qnpg/0dd8S5nDVSVGTvJ75kVc8Rl9NquRHGEn5KX+s+vxkiaoMCtvM7VJtycbH+L/sOEdHNMNN/S5aPdW98gJyRsanTr06q1n0TdpEeKEZTbPZxQl0/udBP7Sg4mBkZoGDUJn4B/UjACPBYUdSj+WtLPYdkNnXavaNdKJLMwRLkf8bvbYIfRfu/AkgQpXQTQKPlAT5mbigQt6Gv1idaEqCKx/t2Jj6Ml4pvscxphbW+JJ/PeE/+zfPcDgwIAzDzcxk5FQGTQeI/XcnQLrHBwjBIwgUHub6zZ20eeSpkn4NIINHeIDKjXbXm6l4c69DsaBaYj31QWCVgtSVzGTCyxHJutSThZzek8+GalLscPWaMffytqcrhkKhsEcpQ2ZokfT/lj/Hau4D3vZmwum81ONBakYUajMQ8oexqOi+h7g=
cache:
  directories:
  - "$HOME/.cache"
before_deploy:
- openssl aes-256-cbc -K $encrypted_315c1c47c01b_key -iv $encrypted_315c1c47c01b_iv
  -in .travis/gpg.key.enc -out .travis/gpg.key -d
deploy:
- skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    tags: true
