language: java
jdk:
- openjdk8
env:
  global:
    - secure: pq7WbSzCJNWuW7bUPjOYXwXnJETCcgx+UVqynL5Wkr0kHYzFapvxDax1IRMhNpY2Cj4YNfA1ms+mKNA+5XmhprOnXTZ+A52r/6S9hURgo9YlVVlhoAwAKfshWP3q3c6/0LqoMc/AyHJ2SWmZqn4RvHmut3YDaTcINaM/TIh0y/JiMAxLOQtuqD3OMBvvXu0TC/vmIN3t1uw16XFj33jUCEtwf+KGkk62zVb1XgP3XwN1uPh3bayBQrOO+z73eVhRS1grgDGpffXsJ0rmRzTCioX4dAr35V5XExHBrLJzLnciLcEnSSMVEbP55gOVscSMyKghwsyvDi2Lorebfi5cZIxoI/yRlfVV62zkKJNHG+wrC9uUNPh24siG5zOjnhS7RR5hLWXCzmzBKyBLKP6uHhsseLHJldxvmt45d9nCuSWc2yfG/mdRFNlkNXvqB8sD6zCmzrlVsDZEsqHSrwrFagUK691IzROhP7AsfrVoyXhO6963Dvcvhym74Jypbakop9GBWaZ0odM/uNS7fmFWb47j0kpKfKPv63jvFfx3/4u4X12ARr/xYc7ZMQ3A21kA3xlnT0jg/xQUoBszL7r3sobRwMHKQ2qwN5bBEhGZCYG/MKOa7mN/FrH45enLAS15pnnyul6Y9U7XvJrlRJwl5uxXr7Vl4T5+ATVqR5oG6Bw=
    - secure: LBkauuVzQFqBrC/Z5OltuFUj+MZGt9ZliqFscweVHgPKHwXXlsig2OoMrS0T1m0dFJV/fPEjn8TTItlwTSWhNl7AUT0h+AA232bvs0bIm72w64R4+DbV5xdZ5Mx+WPiQrYyTfCinP6hdMMhANsl1hGpXgLi51a+Cth+TIuuYveh1kv+E/Mns/4/a1k6PyK3oWZ4CYm/sBuh3YcYlKolyG5o3Ny+IvG2Nng+blF99YGYJdIoADQFyOdxyvAeWLEkNkRLiPs4sOGNgWBgRq39XZ3lGP2TR180wCH/IRZO6j0IU1fdrnjt0NvtShoDngOqfIagrpINE5vFtu4Zy8S5gMh9aGZojQqaS3FCfJBM3DvH0K61P9csXi6VHRwHVN9RBp/yLrPL7c+sb44BzJk2CipDzgIqSmakQoS4VbwTJVZGAYMUlg2EENPvvQsb4KkocG1b3848TEYKzhCwkVZsJusSftImBHOBA4UCz2HDDJ63fbPPnUN0zeyOhZ40cuL15fgpnXxO3wU7uqcX88f247MPQPJnnfH4Hn4Hi3Ahh99q/Dobc9KgmT1Wj2plNybWVzUaXVfF/wbN2eeHz+nxFxlNlmgu2PimxUJI4LhChNxcu243exCmWFEMa8eIpBGySdxnPmZp0dMW538nNB5cLb8b6qzdCXr8iR8udvM8v0ms=
    - secure: G3LbH+gSxH3WtbX9Y9vjMaJcmhCOv5ueMuX4nCzdzqf31hS1dq/+PZC/OAHRx/mKbeWru0J+AOVjPT7t3nb+QEbp+uHWT3iwlmqRRGURHfMhTPnDUPSGlk0NptYrVPiNpiWiZNp6QdEIIlWjQDtb97f8TEqdvd2HvoNp61v6fcf9XnPQ+8QncjcfmsDwpD0IiyEfDJ2fv4p6mEYkVxBKPREl/jaljxyC504gNtaFZOeOL+oIv4AM+t/VzMguSf2qXx5a2X6v5zappfgpbk7b6RJ2BmeosW+HvKOBnAWmlsMbPDuM2hB3x28jJlIITRv0ujeduzbMAB/bBqm0YcnnS21miwvDpfgbPnmMjOOVkdvswJkXW/WvZWf1eTvdWo2JWQiriBANbHbXZNh0PrCxkxvZiS80RFaaRJf8iUdWijYpLBq5W8imWTrZWSHGJrBmQ8VNIyQd9dJwcVvj2sPRP8kG9YbaOii+9VX2/TcOlScG2OcsRLe40NUtBoZpKUoJ8MWGGtAH4SO/G00ihorUxaHbZruPAjufbuW/bSgBA8vxaf2k4dXuLTJxeViexT3pTTKiN+w9Tp803jEvb+NOsKNbar0woYNcGbkqECIDCsCkifb2xOpcfvAjvpvcdooGE3l5A3Sxn3eWj7NwfifRt7ulzoaayxx+MHTAxwJxsO0=
    - secure: TCzycvf1AwIgNZDQAGO4/OpaU+f3YL11Imq1ETwNDGzAdKmhGW/6x7xyfOAvlmPqukyqQJ/nZ2SllQFOtG3e3fIOUJ9LzU9nmeZ0ve4bXu4Qi4+DC+bR2UZ50/bNNVennIfviw77/XcfR1nFIJtsK2zzcexRkSUO7H4Ywk3WlpyXszJwJmxh6NPX4I9AtN7vSasdh7biy8RVHNbfbUwPTaDkb9oFhHLBgpe84r9sARqljDr7TFkvh+/an2FRd1vRxa4JP6m7Slsrn0JMqqDY/aVUV2oRmcrv6cYbYJkW/fCF/uRJ8hMeKtT3EfHUxvY2CY+angbqIdMdYPkoFXShCirwAuCUkjUxP1mZUQ/27+L+zBBrD1WxMK5PPL6ciCb7Or6BjHNM/Y3ciDuyj/NZjLouxh9x83uW7YIj5HnjIaRj7cVY+MkK/yfi2uGquq8jaFC/t2OMpRI8E2mLsDTFZYiGvXrnnajYyNNXHj1YbwNVDz+VAETyQT3MB8ydSoXaGWimX/qc9sU7pxGfrKBc3IErgjDuUstPvyNtD68kIk583akKBnjbEp6ZSf7U0bqDJtM+sKpN+jsQtcZEMc+CS2Lojwm0oQeadwZJYKP99vEWn3pt32r8IsPIPIHivbFl37PsfAVt8782fq0DZYr2Pr5fEjjZW8fDOinPEU7oQYY=
cache:
  directories:
  - "$HOME/.cache"
before_deploy:
- openssl aes-256-cbc -K $encrypted_315c1c47c01b_key -iv $encrypted_315c1c47c01b_iv
  -in .travis/gpg.key.enc -out .travis/gpg.key -d
deploy:
- skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    tags: true
